// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Author: Jumbo 
// source: person_info.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UFramework {

  /// <summary>Holder for reflection information generated from person_info.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class PersonInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for person_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PersonInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFwZXJzb25faW5mby5wcm90bxIKdUZyYW1ld29yayIbCgtQRVJTT05fSU5G",
            "TxIMCgRuYW1lGAEgASgMIjsKEVBFUlNPTl9JTkZPX0FSUkFZEiYKBWl0ZW1z",
            "GAEgAygLMhcudUZyYW1ld29yay5QRVJTT05fSU5GT2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
            new pbr::GeneratedCodeInfo(typeof(global::UFramework.PERSON_INFO), global::UFramework.PERSON_INFO.Parser, new[]{ "Name" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::UFramework.PERSON_INFO_ARRAY), global::UFramework.PERSON_INFO_ARRAY.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PERSON_INFO : pb::IMessage<PERSON_INFO> {
    private static readonly pb::MessageParser<PERSON_INFO> _parser = new pb::MessageParser<PERSON_INFO>(() => new PERSON_INFO());
    public static pb::MessageParser<PERSON_INFO> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::UFramework.PersonInfoReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public PERSON_INFO() {
      OnConstruction();
    }

    partial void OnConstruction();

    public PERSON_INFO(PERSON_INFO other) : this() {
      name_ = other.name_;
    }

    public PERSON_INFO Clone() {
      return new PERSON_INFO(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private pb::ByteString name_ = pb::ByteString.Empty;
    /// <summary>
    /// * 姓名 
    /// </summary>
    public pb::ByteString Name {
      get { return name_; }
      set {
        name_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as PERSON_INFO);
    }

    public bool Equals(PERSON_INFO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.Default.Format(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Name);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Name);
      }
      return size;
    }

    public void MergeFrom(PERSON_INFO other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PERSON_INFO_ARRAY : pb::IMessage<PERSON_INFO_ARRAY> {
    private static readonly pb::MessageParser<PERSON_INFO_ARRAY> _parser = new pb::MessageParser<PERSON_INFO_ARRAY>(() => new PERSON_INFO_ARRAY());
    public static pb::MessageParser<PERSON_INFO_ARRAY> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::UFramework.PersonInfoReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public PERSON_INFO_ARRAY() {
      OnConstruction();
    }

    partial void OnConstruction();

    public PERSON_INFO_ARRAY(PERSON_INFO_ARRAY other) : this() {
      items_ = other.items_.Clone();
    }

    public PERSON_INFO_ARRAY Clone() {
      return new PERSON_INFO_ARRAY(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::UFramework.PERSON_INFO> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::UFramework.PERSON_INFO.Parser);
    private readonly pbc::RepeatedField<global::UFramework.PERSON_INFO> items_ = new pbc::RepeatedField<global::UFramework.PERSON_INFO>();
    public pbc::RepeatedField<global::UFramework.PERSON_INFO> Items {
      get { return items_; }
    }

    public override bool Equals(object other) {
      return Equals(other as PERSON_INFO_ARRAY);
    }

    public bool Equals(PERSON_INFO_ARRAY other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.Default.Format(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
    }

    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      return size;
    }

    public void MergeFrom(PERSON_INFO_ARRAY other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
