# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='person_info.proto',
  package='tnt_deploy',
  serialized_pb='\n\x11person_info.proto\x12\ntnt_deploy\",\n\x0bPERSON_INFO\x12\r\n\x02id\x18\x01 \x02(\r:\x01\x30\x12\x0e\n\x04name\x18\x02 \x01(\x0c:\x00\";\n\x11PERSON_INFO_ARRAY\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.tnt_deploy.PERSON_INFO')




_PERSON_INFO = descriptor.Descriptor(
  name='PERSON_INFO',
  full_name='tnt_deploy.PERSON_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='tnt_deploy.PERSON_INFO.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='tnt_deploy.PERSON_INFO.name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=True, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=77,
)


_PERSON_INFO_ARRAY = descriptor.Descriptor(
  name='PERSON_INFO_ARRAY',
  full_name='tnt_deploy.PERSON_INFO_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='tnt_deploy.PERSON_INFO_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=79,
  serialized_end=138,
)

_PERSON_INFO_ARRAY.fields_by_name['items'].message_type = _PERSON_INFO
DESCRIPTOR.message_types_by_name['PERSON_INFO'] = _PERSON_INFO
DESCRIPTOR.message_types_by_name['PERSON_INFO_ARRAY'] = _PERSON_INFO_ARRAY

class PERSON_INFO(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERSON_INFO
  
  # @@protoc_insertion_point(class_scope:tnt_deploy.PERSON_INFO)

class PERSON_INFO_ARRAY(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERSON_INFO_ARRAY
  
  # @@protoc_insertion_point(class_scope:tnt_deploy.PERSON_INFO_ARRAY)

# @@protoc_insertion_point(module_scope)
